using System;
using System.Linq;
using Content.Shared.DeadSpace.AppHub;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.AppHub;

[GenerateTypedNameReferences]
public sealed partial class NtSoftwareHubLaptopMenu : DefaultWindow
{
    public event Action<string>? OnPurchasePressed;

    public NtSoftwareHubLaptopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LaptopTitleLabel.Text = Loc.GetString("nt-software-hub-laptop-title");
    }

    public void UpdateState(NtSoftwareHubLaptopUiState state)
    {
        BalanceLabel.Text = Loc.GetString("nt-software-hub-laptop-balance",
            ("balance", state.TotalLikes - state.SpentLikes),
            ("total", state.TotalLikes),
            ("spent", state.SpentLikes));

        PopulateProgramList(state.Entries, state.TotalLikes - state.SpentLikes);
    }

    private void PopulateProgramList(List<NtSoftwareHubLaptopCatalogEntry> entries, int balance)
    {
        ProgramListContainer.RemoveAllChildren();

        if (entries.Count == 0)
        {
            ProgramListContainer.AddChild(new Label
            {
                Text = Loc.GetString("nt-software-hub-laptop-no-programs"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
            });
            return;
        }

        foreach (var entry in entries.OrderBy(e => e.Name))
        {
            var card = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(2),
            };
            card.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1a1a1aFF"),
                BorderColor = Color.FromHex("#444444FF"),
                BorderThickness = new Thickness(1),
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(6, 4),
                SeparationOverride = 8,
            };

            var infoColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 2,
            };

            var nameLabel = new Label
            {
                Text = entry.Name,
                StyleClasses = { "LabelBig" },
                HorizontalExpand = true,
            };
            infoColumn.AddChild(nameLabel);

            var descLabel = new Label
            {
                Text = entry.Description,
                FontColorOverride = Color.FromHex("#AAAAAA"),
                HorizontalExpand = true,
            };
            infoColumn.AddChild(descLabel);

            row.AddChild(infoColumn);

            var costLabel = new Label
            {
                Text = Loc.GetString("nt-software-hub-laptop-cost", ("cost", entry.LikesCost)),
                FontColorOverride = Color.FromHex("#FFD700"),
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(costLabel);

            var actionButton = new Button
            {
                MinWidth = 110,
                VerticalAlignment = VAlignment.Center,
            };

            if (entry.IsPurchased)
            {
                actionButton.Text = Loc.GetString("nt-software-hub-laptop-purchased");
                actionButton.Disabled = true;
            }
            else
            {
                actionButton.Text = Loc.GetString("nt-software-hub-laptop-buy");
                if (balance < entry.LikesCost)
                    actionButton.Disabled = true;

                var capturedId = entry.Id;
                actionButton.OnPressed += _ => OnPurchasePressed?.Invoke(capturedId);
            }

            row.AddChild(actionButton);
            card.AddChild(row);
            ProgramListContainer.AddChild(card);
        }
    }
}
