using System;
using System.Linq;
using Content.Shared.DeadSpace.AppHub;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.AppHub;

[GenerateTypedNameReferences]
public sealed partial class NtSoftwareHubCartridgeFragment : BoxContainer
{
    public event Action<string>? OnInstallPressed;
    public event Action<string>? OnUninstallPressed;
    public event Action<string>? OnCategorySelected;

    private string _currentCategory = "All";

    public NtSoftwareHubCartridgeFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        TitleLabel.Text = Loc.GetString("nt-software-hub-cartridge-title");
        CategoryAll.Text = Loc.GetString("nt-software-hub-category-all");
        CategoryTools.Text = Loc.GetString("nt-software-hub-category-tools");
        CategoryEquipment.Text = Loc.GetString("nt-software-hub-category-equipment");
        CategoryGames.Text = Loc.GetString("nt-software-hub-category-games");

        CategoryAll.OnPressed += _ => SetCategory("All");
        CategoryTools.OnPressed += _ => SetCategory("Tools");
        CategoryEquipment.OnPressed += _ => SetCategory("Equipment");
        CategoryGames.OnPressed += _ => SetCategory("Games");
    }

    public void UpdateState(NtSoftwareHubCartridgeUiState state)
    {
        _currentCategory = state.SelectedCategory;

        StatusLabel.Text = Loc.GetString("nt-software-hub-status-connected");
        StatusLabel.FontColorOverride = Color.FromHex("#88FF88");

        MemoryLabel.Text = Loc.GetString("nt-software-hub-memory", ("used", state.UsedDiskSpace), ("max", state.MaxDiskSpace));
        MemoryBar.MaxValue = Math.Max(state.MaxDiskSpace, 1);
        MemoryBar.Value = state.UsedDiskSpace;

        UpdateCategoryButtons();
        PopulateProgramList(state.CatalogEntries);
    }

    private void SetCategory(string category)
    {
        _currentCategory = category;
        OnCategorySelected?.Invoke(category);
    }

    private void UpdateCategoryButtons()
    {
        var buttons = new[] { ("All", CategoryAll), ("Tools", CategoryTools), ("Equipment", CategoryEquipment), ("Games", CategoryGames) };
        foreach (var (cat, btn) in buttons)
        {
            btn.Modulate = cat == _currentCategory ? Color.FromHex("#00FF88") : Color.White;
        }
    }

    private void PopulateProgramList(List<AppHubCatalogEntry> entries)
    {
        ProgramListContainer.RemoveAllChildren();

        if (entries.Count == 0)
        {
            ProgramListContainer.AddChild(new Label
            {
                Text = Loc.GetString("nt-software-hub-no-programs"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
            });
            return;
        }

        foreach (var entry in entries.OrderBy(e => e.Name))
        {
            var card = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(2),
            };
            card.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1a1a1aFF"),
                BorderColor = Color.FromHex("#444444FF"),
                BorderThickness = new Thickness(1),
            };

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(6, 4),
                SeparationOverride = 8,
            };

            var infoColumn = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 2,
            };

            var nameLabel = new Label
            {
                Text = entry.Name,
                StyleClasses = { "LabelBig" },
                HorizontalExpand = true,
            };
            infoColumn.AddChild(nameLabel);

            var descLabel = new Label
            {
                Text = entry.Description,
                FontColorOverride = Color.FromHex("#AAAAAA"),
                HorizontalExpand = true,
                ClipText = true,
            };
            infoColumn.AddChild(descLabel);

            row.AddChild(infoColumn);

            var actionButton = new Button
            {
                MinWidth = 90,
                VerticalAlignment = VAlignment.Center,
            };

            if (entry.IsInstalled)
            {
                actionButton.Text = Loc.GetString("nt-software-hub-uninstall");
                var capturedId = entry.Id;
                actionButton.OnPressed += _ => OnUninstallPressed?.Invoke(capturedId);
            }
            else
            {
                actionButton.Text = Loc.GetString("nt-software-hub-install");
                var capturedId = entry.Id;
                actionButton.OnPressed += _ => OnInstallPressed?.Invoke(capturedId);
            }

            row.AddChild(actionButton);
            card.AddChild(row);
            ProgramListContainer.AddChild(card);
        }
    }
}
